# Generated by Django 5.2.8 on 2025-11-16 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dispozitiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('vendor_id', models.CharField(max_length=100, unique=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispozitive', to='api.camera')),
            ],
        ),
        migrations.CreateModel(
            name='TipDispozitiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_tip', models.CharField(max_length=50, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StareDispozitiv',
            fields=[
                ('dispozitiv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stare', serialize=False, to='api.dispozitiv')),
                ('stare', models.JSONField(default=dict)),
                ('ultima_actualizare', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('membri', models.ManyToManyField(related_name='locatii', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='locatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camere', to='api.locatie'),
        ),
        migrations.AddField(
            model_name='dispozitiv',
            name='tip_dispozitiv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipdispozitiv'),
        ),
    ]
