# Generated by Django 5.2.8 on 2025-11-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispozitiv',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='dispozitiv',
            name='tip_dispozitiv',
        ),
        migrations.RemoveField(
            model_name='staredispozitiv',
            name='dispozitiv',
        ),
        migrations.RemoveField(
            model_name='locatie',
            name='membri',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='TipDispozitiv',
        ),
        migrations.DeleteModel(
            name='Dispozitiv',
        ),
        migrations.DeleteModel(
            name='StareDispozitiv',
        ),
        migrations.DeleteModel(
            name='Locatie',
        ),
    ]
