# Generated by Django 5.2.9 on 2025-12-13 12:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accent_color',
            field=models.CharField(blank=True, default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.avatar_upload_path),
        ),
    ]
