# Generated by custom migration

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Create DeviceType model
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(default=dict, help_text="JSON schema defining sensors and actions, e.g., {'sensors': ['temperature'], 'actions': ['set_temp']}")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        # Step 2: Add custom_data field to Device
        migrations.AddField(
            model_name='device',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text="Current values for sensors defined in device type schema, e.g., {'temperature': 72}"),
        ),
        # Step 3: Rename old device_type field to device_type_old
        migrations.RenameField(
            model_name='device',
            old_name='device_type',
            new_name='device_type_old',
        ),
        # Step 4: Add new device_type as nullable ForeignKey temporarily
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='api.devicetype'),
        ),
    ]
