# Generated by custom migration

from django.db import migrations


def migrate_device_types(apps, schema_editor):
    """Create DeviceType objects from existing device_type strings and link devices."""
    Device = apps.get_model('api', 'Device')
    DeviceType = apps.get_model('api', 'DeviceType')
    
    # Get all devices
    devices = Device.objects.all()
    
    # Create a mapping of (user, type_name) -> DeviceType
    device_type_cache = {}
    
    for device in devices:
        if device.device_type_old and device.user:
            cache_key = (device.user.id, device.device_type_old)
            
            # Get or create DeviceType
            if cache_key not in device_type_cache:
                device_type, created = DeviceType.objects.get_or_create(
                    name=device.device_type_old,
                    user=device.user,
                    defaults={
                        'description': f'Migrated from existing device type: {device.device_type_old}',
                        'schema': {'sensors': [], 'actions': []}
                    }
                )
                device_type_cache[cache_key] = device_type
            
            # Link device to DeviceType
            device.device_type = device_type_cache[cache_key]
            device.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - copy DeviceType name back to device_type_old."""
    Device = apps.get_model('api', 'Device')
    
    for device in Device.objects.all():
        if device.device_type:
            device.device_type_old = device.device_type.name
            device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_devicetype_model'),
    ]

    operations = [
        migrations.RunPython(migrate_device_types, reverse_migration),
    ]
