# Generated by Django 6.0 on 2026-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevicetype',
            name='definition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
