# Generated by custom migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_migrate_device_types'),
    ]

    operations = [
        # Step 1: Remove the old device_type_old field
        migrations.RemoveField(
            model_name='device',
            name='device_type_old',
        ),
        # Step 2: Make device_type non-nullable
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='api.devicetype'),
        ),
    ]
