# Generated by Django 6.0 on 2026-01-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdevicetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
    ]
