# Generated by Django 6.0 on 2026-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_customdevicetype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='icon',
            field=models.CharField(blank=True, default='fa-cube', help_text='FontAwesome icon class (e.g., fa-lightbulb)', max_length=50),
        ),
    ]
