# Generated by Django 6.0 on 2026-01-13 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_device_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='Frontend grid layout configuration (x, y, w, h)')),
                ('device_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_template', to='api.customdevicetype')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('TOGGLE', 'Toggle Switch'), ('SLIDER', 'Slider'), ('GAUGE', 'Gauge')], max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('variable_mapping', models.CharField(help_text='MQTT/API variable key (e.g., relay_1)', max_length=50)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('step', models.FloatField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='api.devicecardtemplate')),
            ],
            options={
                'unique_together': {('template', 'variable_mapping')},
            },
        ),
    ]
