# Generated by Django 6.0 on 2026-01-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_devicecardtemplate_devicecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevicetype',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if denied Admin approval', null=True),
        ),
    ]
