# Generated by Django 6.0 on 2026-01-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_customdevicetype_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_state',
            field=models.JSONField(blank=True, default=dict, help_text="Current state of device controls (e.g., {'relay_1': True})"),
        ),
    ]
