# Generated by Django 6.0.1 on 2026-02-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_device_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='size',
            field=models.CharField(blank=True, choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], help_text='Widget size: sm, md, or lg', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='devicecontrol',
            name='unit',
            field=models.CharField(blank=True, help_text='Display unit (e.g., °C, %, lux, ppm)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='devicecontrol',
            name='variant',
            field=models.CharField(blank=True, choices=[('row', 'Row'), ('square', 'Square'), ('compact', 'Compact')], help_text='Display variant: row, square, or compact', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicecontrol',
            name='widget_type',
            field=models.CharField(choices=[('TOGGLE', 'Toggle Switch'), ('SLIDER', 'Slider'), ('BUTTON', 'Button'), ('GAUGE', 'Gauge'), ('TEMPERATURE', 'Temperature Sensor'), ('HUMIDITY', 'Humidity Sensor'), ('MOTION', 'Motion Sensor'), ('LIGHT', 'Light Sensor'), ('CO2', 'CO2 Sensor'), ('PRESSURE', 'Pressure Sensor'), ('POWER', 'Power Meter'), ('BATTERY', 'Battery Level'), ('STATUS', 'Status Indicator')], max_length=20),
        ),
    ]
