# Generated by Django 6.0.1 on 2026-02-02 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_extended_widget_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customdevicetype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='customdevicetype',
            name='approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], db_index=True, default='offline', max_length=10),
        ),
        migrations.AddIndex(
            model_name='customdevicetype',
            index=models.Index(fields=['approved', 'created_at'], name='devicetype_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'status'], name='device_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['room'], name='device_room_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='device_type_idx'),
        ),
    ]
