# Generated by Django 6.0.1 on 2026-02-02 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('device_type_pending', 'Device Type Pending'), ('device_type_approved', 'Device Type Approved'), ('device_type_denied', 'Device Type Denied'), ('device_offline', 'Device Offline'), ('device_online', 'Device Online'), ('device_error', 'Device Error'), ('system', 'System'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('reference_data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='The user who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'), models.Index(fields=['user', 'notification_type'], name='notif_user_type_idx'), models.Index(fields=['created_at'], name='notif_created_idx')],
            },
        ),
    ]
