# Generated by Django 6.0.1 on 2026-02-04 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_notification_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevicetype',
            name='proposed_by',
            field=models.ForeignKey(blank=True, help_text='User who proposed this device type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_device_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
