# Generated by Django 6.0.1 on 2026-02-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlayout',
            name='device_order',
            field=models.CharField(choices=[('room', 'Group by Room'), ('type', 'Group by Device Type'), ('status', 'Group by Status'), ('name', 'Alphabetical by Name'), ('custom', 'Custom Order')], default='room', help_text='Device grouping/sorting preference for the dashboard.', max_length=20),
        ),
    ]
