# Generated by Django 6.0.1 on 2026-02-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_device_order_to_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC Address (automatic from device)', max_length=17, null=True, unique=True),
        ),
    ]
