# Generated by Django 6.0.2 on 2026-02-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_device_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time the device reported state'),
        ),
    ]
