# Generated by Django 6.0.5 on 2026-05-09 07:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_device_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevicetype',
            name='documentation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customdevicetype',
            name='firmware_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customdevicetype',
            name='wiring_diagram_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.wiring_diagram_upload_path),
        ),
        migrations.AddField(
            model_name='customdevicetype',
            name='wiring_diagram_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
