# Generated by Django 6.0.5 on 2026-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_seed_default_device_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevicetype',
            name='wiring_diagram_base64',
            field=models.TextField(blank=True, default='', help_text='Base64 data URI of wiring diagram image (portable, used for export/import)'),
        ),
    ]
