# Generated by Django 6.0.5 on 2026-05-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_migrate_wiring_images_to_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdevicetype',
            name='documentation_images_base64',
            field=models.JSONField(blank=True, default=list, help_text='Array of {filename, data} for documentation images (portable)'),
        ),
    ]
