# Generated by Django 6.0.5 on 2026-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_documentation_images_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdevicetype',
            name='wiring_diagram_image',
        ),
        migrations.AlterField(
            model_name='customdevicetype',
            name='documentation_images_base64',
            field=models.JSONField(blank=True, default=list, help_text='Array of {filename, data} for documentation images, stored directly in DB'),
        ),
        migrations.AlterField(
            model_name='customdevicetype',
            name='wiring_diagram_base64',
            field=models.TextField(blank=True, default='', help_text='Base64 data URI of wiring diagram image, stored directly in DB'),
        ),
    ]
