# Generated by Django 6.0.5 on 2026-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_viewer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.CharField(blank=True, default='fa-door-open', help_text='FontAwesome icon class (e.g., fa-bed, fa-couch)', max_length=50),
        ),
    ]
