# Generated by Django 6.0.6 on 2026-06-04 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_dedupe_rooms_add_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the solar system', max_length=100)),
                ('base_url', models.URLField(help_text='Base link to the vendor API, e.g. http://fronius-server:9999', max_length=500)),
                ('provider', models.CharField(choices=[('fronius', 'Fronius Solar API V1')], default='fronius', help_text='Vendor adapter used to normalize the raw JSON', max_length=30)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('api_version', models.CharField(blank=True, default='', max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text="Cached capability flags, e.g. {'history': false, 'battery': true}")),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last successful fetch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('base_url', 'user')},
            },
        ),
    ]
