# Generated by Django 6.0.6 on 2026-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_solarsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsystem',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict, help_text="Cached capability flags, e.g. {'battery': true, 'meter': true}"),
        ),
    ]
