# Generated by Django 6.0.6 on 2026-06-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_solarsystem_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecontrol',
            name='widget_type',
            field=models.CharField(choices=[('TOGGLE', 'Toggle Switch'), ('SLIDER', 'Slider'), ('BUTTON', 'Button'), ('GAUGE', 'Gauge'), ('TEMPERATURE', 'Temperature Sensor'), ('HUMIDITY', 'Humidity Sensor'), ('PRESSURE', 'Pressure Sensor'), ('POWER', 'Power Meter'), ('BATTERY', 'Battery Level'), ('STATUS', 'Status Indicator'), ('MOTION', 'Motion Sensor (Coming Soon)'), ('CO2', 'CO2 Sensor (Coming Soon)'), ('LIGHT', 'Light Sensor (Coming Soon)')], max_length=20),
        ),
    ]
